- name: Install Helm client
  shell: |
    curl -LO https://git.io/get_helm.sh
    chmod 700 get_helm.sh
    ./get_helm.sh

- name: Copy Tiller RBAC files
  template:
    src: "tiller-rbac.yml.j2"
    dest: /tmp/tiller-rbac.yml

- name: Apply Tiller RBAC files
  command: "kubectl apply -f /tmp/tiller-rbac.yml"

- name: Initialize Heml and deploy Tiller
  command: "helm init --wait --tiller-namespace {{ helm_namespace }} --service-account tiller"
