apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: example-jib-maven
spec:
  taskRef:
    name: jib-maven
  inputs:
    params:
      - name: DIRECTORY
        value: ./examples/helloworld
    resources:
      - name: source
        resourceRef:
          name: fruit-client-sb-git
  outputs:
    resources:
      - name: image
        resourceRef:
          name: example-image
