- name: Remove Halkyon web site k8s resources
  shell: |
    {{ client_tool }} {{ k8s_config }} delete -f https://raw.githubusercontent.com/halkyonio/halkyonio-site/{{ halkyon_version }}/config/common.yml -n {{ halkyon_namespace }}
    {{ client_tool }} {{ k8s_config }} delete -f https://raw.githubusercontent.com/halkyonio/halkyonio-site/{{ halkyon_version }}/config/ingress.yml -n {{ halkyon_namespace }}
