apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: jib-buildah-push
spec:
  taskRef:
    name: jib-maven
  inputs:
    # params:
    # - name: baseImage
    #   value: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
    # - name: verifyTLS
    #   value: "false"
    # - name: contextFolder
    #   value: /workspace/
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: revision
          value: master
        - name: url
          value: https://github.com/che-samples/console-java-simple
  outputs:
    resources:
    - name: image
      resourceSpec:
        type: image
        params:
        - name: url
          value: docker-registry.default.svc:5000/demo/spring-boot-jib
