apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: jib-maven
spec:
  inputs:
    params:
      - name: DIRECTORY
        description: The directory containing the app, relative to the source repository root
        default: .
      - name: CACHE
        description: The name of the volume for caching Maven artifacts and base image layers
        default: empty-dir-volume
    resources:
      - name: source
        type: git
        # targetPath: /
  outputs:
    resources:
      - name: image
        type: image

  steps:
    - name: cacert
      image: gcr.io/cloud-builders/mvn
      command: ["/bin/bash"]
      # args: ["-c", "$JAVA_HOME/bin/keytool -alias dockerregistry -import -file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -keystore /builder/home/trust.jks -storepass changeit -noprompt"]
      # args: ["-c", "$JAVA_HOME/bin/keytool -import -storepass changeit -keystore $JAVA_HOME/lib/security/cacerts -alias certificate.cer -file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -noprompt"]
      args: ["-c", "$JAVA_HOME/bin/keytool -importcert -storepass changeit -file /etc/secrets/registry.crt -noprompt"]
      volumeMounts:
      - mountPath: /etc/secrets
        name: volume-docker-secret
    - name: build-and-push
      image: gcr.io/cloud-builders/mvn
      command:
        - mvn
        - compile
        # - -X
        - com.google.cloud.tools:jib-maven-plugin:build
        - -Duser.home=/builder/home
        #- -Djavax.net.ssl.trustStore=/builder/home/trust.jks
        #- -Djavax.net.ssl.trustStorePassword=changeit
        - -Dimage=${outputs.resources.image.url}
        - -Djib.allowInsecureRegistries=true
      workingDir: /workspace/source/${inputs.params.DIRECTORY}
      volumeMounts:
        - name: ${inputs.params.CACHE}
          mountPath: /builder/home/.m2
          subPath: m2-cache
        - name: ${inputs.params.CACHE}
          mountPath: /builder/home/.cache
          subPath: jib-cache

  volumes:
    - name: empty-dir-volume
      emptyDir: {}
    - name: volume-docker-secret
      secret:
        defaultMode: 420
        secretName: docker-registry-cert
