- set_fact:
    k8s_config: "--kubeconfig '/etc/kubernetes/admin.conf'"
    client_tool: kubectl
  when: not isOpenshift | bool

- debug:
    var: k8s_config

- include_tasks: install1.yml
  when: not remove | bool

- include_tasks: remove.yml
  when: remove | bool
