apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: use-image-scc-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: image-scc-privileged-role
subjects:
  - kind: ServiceAccount
    name: default
