apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: jib-push
spec:
  taskRef:
    name: jib-maven
  inputs:
    params:
    - name: USERNAME
      value: USERNAME
    - name: PASSWORD
      value: PASSWORD
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: revision
          value: master
        - name: url
          value: https://github.com/cmoulliard/hello-world-springboot
  outputs:
    resources:
    - name: image
      resourceSpec:
        type: image
        params:
        - name: url
          value: docker-registry.default.svc:5000/cmoullia/spring-boot-jib
