---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: spring-boot-example-git
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/snowdrop/rest-http-example
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: spring-boot-example-image
spec:
  type: image
  params:
  - name: url
   value: quay.io/snowdrop/spring-boot-example
