- set_fact:
    restart_script: /usr/local/bin/master-restart

- name: Check if restart script exists
  stat:
    path: "{{ restart_script }}"
  register: sc

- name: Use provided restart script
  command: "{{ restart_script }} api"
  when: sc.stat.exists == true

- name: Attempt to restart docker container
  command: "docker restart origin"
  when: sc.stat.exists == false

- name: Wait for master to stand up
  pause:
    seconds: 60


