---
- name: Create k8s config folder for os user
  file:
    path: ".kube"
    state: directory
    mode: '0755'

- name: Copy k8s config file
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: ".kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    remote_src: yes
  become: yes

- set_fact:
    k8s_server: "https://{{ ansible_ssh_host }}:6443"
    inventory_location: "{{ lookup('env', 'PWD') }}/inventory"

- name: Get secret name
  shell: |
    kubectl --kubeconfig=$HOME/.kube/config -n kube-system get secret | grep default-token | awk '{print $1}'
  register: get_secret_out

- set_fact:
    k8s_secret_name: "{{ get_secret_out.stdout }}"

- name: Get CA
  shell: |
    kubectl --kubeconfig=$HOME/.kube/config -n kube-system get secret/{{ k8s_secret_name }} -o jsonpath='{.data.ca\.crt}'
  register: get_ca_out

- set_fact:
    k8s_ca: "{{ get_ca_out.stdout }}"

- name: Get token
  shell: |
    kubectl --kubeconfig=$HOME/.kube/config -n kube-system get secret/{{ k8s_secret_name }} -o jsonpath='{.data.token}' | base64 -d
  register: get_token_out

- set_fact:
    k8s_token: "{{ get_token_out.stdout }}"

- name: Get namespace
  shell: |
    kubectl --kubeconfig=$HOME/.kube/config -n kube-system get secret/{{ k8s_secret_name }} -o jsonpath='{.data.namespace}' | base64 -d
  register: get_namespace_out

- set_fact:
    k8s_namespace: "{{ get_namespace_out.stdout }}"

- name: Save config
  template:
    src: "k8s-config.yml.j2"
    dest: "/tmp/{{ k8s_config_filename }}"
#    dest: "{{ inventory_location }}/{{ k8s_config_filename }}"
  delegate_to: localhost
  become: no

- name: Print kubernetes config file location
  debug:
    msg:
      - "You can use the following Kubernetes config file to interact with remote cluster via kubectl"
      - "{{ inventory_location }}/{{ k8s_config_filename }}"
...