- name: Check if Kind Binary is Present
  stat:
    path: "{{ kind_binary }}"
  register: kind_binary_present

- name: Download Kind binary from github release
  get_url:
    url: "https://github.com/kubernetes-sigs/kind/releases/download/{{ kind_archive_name }}"
    dest: "{{ kind_binary }}"
    mode: '0755'
  when: not kind_binary_present.stat.exists

- name: Create Cluster
  shell: |
    kind create cluster \
      --image=kindest/node:{{ kind_k8s_version }} \
      --name {{ kind_cluster_name }} \
      --loglevel=debug

#- name: Setup kube config
#  shell: |
#    kind get kubeconfig-path --name={{ kind_cluster_name }}
#    mkdir -p $HOME/.kube
#    cp -i $(kind get kubeconfig-path --name={{ kind_cluster_name }}) $HOME/.kube/config
#    sudo chown $(id -u):$(id -g) $HOME/.kube/config
