- name: Remove Kind cluster
  command: kind delete cluster --name={{ kind_cluster_name }}

- name: Remove the docker registry container when requested.
  include_tasks: docker_container_registry.yml
  when: registry | bool
