apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: buildah
spec:
  inputs:
    resources:
    - name: workspace-git
      targetPath: /
      type: git
    params:
    - name: dockerfile
      description: The path to the dockerfile to build
      default: Dockerfile
    - name: verifyTLS
      description: Verify registry certificates
      default: "true"
    - name: contextFolder
      description: The path of the context to build
      default: .
  outputs:
    resources:
    - name: image
      type: image
  steps:
  - name: build
    image: quay.io/openshift-pipeline/buildah:testing
    command:
      - buildah
    args: 
      - bud
      - --layers
      - --tls-verify=${inputs.params.verifyTLS}
      - -f
      - ${inputs.params.dockerfile}
      - -t
      - ${outputs.resources.image.url}
      - ${inputs.params.contextFolder}
    volumeMounts:
    - name: libcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true
  - name: push
    image: quay.io/openshift-pipeline/buildah:testing
    command:
      - buildah
    args: 
      - push
      - --tls-verify=${inputs.params.verifyTLS}
      - ${outputs.resources.image.url}
    volumeMounts:
    - name: libcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true
  volumes:
    - name: libcontainers
      emptyDir: {}
