---
# file: hetzner-create-server.yml
# Optional variables:
- name:  Create hetzner server
  hosts: localhost
  gather_facts: yes
  vars_prompt:
    - name: vm_name
      prompt: Name of the VM being created [vm_name]
      private: no
      when: " vm_name is not defined "

    - name: salt_text
      prompt: Salt
      private: yes
      when: " salt_text is not defined "

  pre_tasks:

    - name: Get vm host vars
      set_fact:
        my_hostvars: "{{ hostvars[vm_name] }}"

    - name: Set default hetzner_context_name if it is not defined
      set_fact:
        hetzner_context_name: "snowdrop"
      when: hetzner_context_name is not defined

  tasks:
    - name: "Actuvate hetzner context"
      include_role:
        name: "hetzner/activate_context"
      vars:
        context_name: "{{ hetzner_context_name }}"

    - include_role:
        name: hetzner/create_server
      vars:
        vm_name: "{{ vm_name }}"
        os_user: "{{ my_hostvars.ansible_user }}"
        context_name: "{{ hetzner_context_name }}"

    - name: Update inventory
      include_role:
        name: "passstore/ansible_inventory"
        tasks_from: "add_variable"
      vars:
        pass_l1: "snowdrop"
        pass_l2: "hetzner"
        pass_l3: "{{ vm_name }}"
        var_name: "ansible_ssh_host"
        var_value: "{{ ip_address }}"

  post_tasks:

    - name: Refresh the inventory
      meta: refresh_inventory

    - name: Get vm host vars
      set_fact:
        my_hostvars: "{{ hostvars[vm_name] }}"

- name:  Wait for the VM to boot and we can ssh
  hosts: "{{ vm_name }}"
  gather_facts: no

  tasks:
    - name: ping hosts
      wait_for_connection:
        timeout: 60

  post_tasks:
    - name: "DON'T FORGET TO SECURE YOUR SERVER"
      debug:
        msg: "Trying to start start server securization automatically For manual execution: $ ansible-playbook ansible/playbook/sec_host.yml -e vm_name={{ vm_name }} -e provider=hetzner"
...
