---
# file: hetzner-delete-server.yml
- name: Delete hetzner server
  hosts: localhost
  gather_facts: yes
  vars_prompt:
    - name: vm_name
      prompt: Name of the VM being removed [vm_name]
      private: no
      when: " vm_name is not defined "

  pre_tasks:
    - name: Get vm host vars
      set_fact:
        my_hostvars: "{{ hostvars[vm_name] }}"
      tags: [always]

  roles:
    - role: hetzner/activate_context
      context_name: "{{ hetzner_context_name }}"
      tags: [always]

    - role: hetzner/delete_server
      vm_name: "{{ vm_name }}"
      tags: [never,vm_delete]
...
