---
# file: hetzner-create-hcloud-server.yml
# Optional variables:
#  . vm_delete: Deletes the virtual machine prior to creating it.
#  . pass_store_dir: Directory containing the password store.
#  . server_type:
#  . vm_image:
- name: Delete hetzner server
  hosts: localhost
  gather_facts: yes
  vars_prompt:
    - name: vm_name
      prompt: vm name
      private: no
      when: " vm_name is not defined "

  pre_tasks:

    - name: Get vm host vars
      set_fact:
        my_hostvars: "{{ hostvars[vm_name] }}"
      tags: [always]

  roles:
    - role: hetzner/activate_context
      context_name: "{{ hetzner_context_name }}"

    - role: hetzner/delete_server
      vm_name: "{{ vm_name }}"
      tags: [never,vm_delete]

...
