- name: Set client tool to oc when the cluster is Openshift
  set_fact:
    client_tool: oc
  when: isOpenshift | bool

- name: Set client tool to kubectl when the cluster is Kubernetes
  set_fact:
    client_tool: kubectl
  when: not isOpenshift | bool

- name: Set release url for non latest
  set_fact:
    prefix: "previous/{{ tekton_release_version }}"
  when: tekton_release_version != "latest"

- name: Set release url for latest
  set_fact:
    prefix: latest
  when: tekton_release_version == "latest"

- include_tasks: install.yml
  when: not remove | bool

- include_tasks: remove.yml
  when: remove | bool
