all:
  children:
    hetzner:
      vars:
        pass_provider: hetzner
    k8s:
      children:
        masters:
          vars:
            firewalld_public_ports:
              - 6443/tcp
              - 10250/tcp
              - 10255/tcp
              - 8472/udp
              - 30000-32767/tcp
            firewalld_public_services:
              - http
              - https
            pod_subnet: 10.244.0.0/16
            service_subnet: 10.96.0.0/12
        nodes:
          vars:
            firewalld_public_ports:
              - 6443/tcp
              - 2379-2380/tcp
              - 10250/tcp
              - 10251/tcp
              - 10252/tcp
              - 10255/tcp
              - 8472/udp
            firewalld_public_services:
              - http
              - https
            pod_subnet: 10.244.0.0/16
            service_subnet: 10.96.0.0/12
        k8s_116:
          vars:
            k8s_version: 1.16.7
            k8s_dashboard_version: v2.0.0-rc5
        k8s_115:
          vars:
            k8s_version: 1.15.9
            k8s_dashboard_version: v2.0.0-rc5
      vars:
        isOpenshift: false
  vars:
    timezone: Europe/Madrid
    # Default pass_provider to group pass records. This shouldn't be used.
    pass_provider: tbd
