- name: Remove ocp4 console
  shell: |
    kubectl --kubeconfig=$HOME/.kube/config delete clusterrolebinding/ocp4-console-rbac
    kubectl --kubeconfig=$HOME/.kube/config delete service/ocp4-console -n default
    kubectl --kubeconfig=$HOME/.kube/config delete ingress/ocp4-console -n default
    kubectl --kubeconfig=$HOME/.kube/config delete Deployment/ocp4-console -n default
