version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:latest

    steps:
      - checkout

      - run:
          name: Install Ansible
          command: |
            #sudo apt update
            #sudo apt -yqq install software-properties-common
            #sudo apt-add-repository -y --update ppa:ansible/ansible
            #sudo apt -yqq install ansible

            #sudo apt -yqq install software-properties-common
            #sudo add-apt-repository -y ppa:deadsnakes/ppa
            sudo apt install -yqq python3-pip
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            python get-pip.py --user
            pip3 install --user ansible
