version: 2.1

jobs:
  build:
    docker:
      - image: image: circleci/golang:latest

    steps:
      - checkout

      - run:
          name: Install Ansible
          command: sudo apt install ansible
