version: 2.1

jobs:

  kind:
    #docker:
    #  - image: quay.io/snowdrop/centos-circleci:latest
    machine:
      enabled: true
      docker_layer_caching: true
    environment:
      CLUSTER_NAME: circleci
      GO_VERSION: 1.12.7
      GOPATH: /go
      KIND_VERSION: v0.4.0
      KUBECTL_VERSION: v1.14.0

    steps:
      # - checkout
      # - setup_remote_docker
      # - run:
      #     name: Install Go
      #     command: |
      #       wget https://dl.google.com/go/go$GO_VERSION.linux-amd64.tar.gz && \
      #           tar -C /usr/local -xzf go$GO_VERSION.linux-amd64.tar.gz
      #       mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
      #       export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl

      - run:
          name: Install Kind
          command: |
            KIND_BINARY_URL="https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-linux-amd64"
            wget -O kind "${KIND_BINARY_URL}"
            chmod +x ./kind
            sudo mv ./kind /usr/local/bin/kind

      - run:
          name: Create Kind cluster
          command: |
            set -x
            kind create cluster --image=kindest/node:v1.14.3 --name $CLUSTER_NAME --loglevel=debug

      - run:
          name: Setup kubeconfig file
          command: |
            kind get kubeconfig-path --name=$CLUSTER_NAME
            mkdir -p $HOME/.kube
            cp -i $(kind get kubeconfig-path --name=$CLUSTER_NAME) $HOME/.kube/config
            sudo chown $(id -u):$(id -g) $HOME/.kube/config
            cat /home/circleci/.kube/kind-config-$CLUSTER_NAME

      - run:
          name: Check Cluster state
          command: |
            #kubectl cluster-info
            #kubectl wait -n kube-system --timeout=320s --for condition=Ready -l k8s-app=calico-node pods
            kubectl get nodes -o wide
            kubectl get pods --all-namespaces -o wide
            kubectl get services --all-namespaces -o wide

      - run:
          name: Run e2e tests
          no_output_timeout: 200m
          command: |
            # Fake google.com
            kubectl apply -f .circleci/fake-google-com.yaml
            kubectl wait --timeout=60s --for condition=Ready -l run=my-google pods
            kubectl wait -n kube-system --for=condition=Ready -l k8s-app=kube-dns pods

            # Run e2e tests
            e2e.test --provider=local --kubeconfig=$(kind get kubeconfig-path --name="kind") --ginkgo.focus "\[Conformance\]" --ginkgo.skip "Alpha|Kubectl|\[(Disruptive|Feature:[^\]]+|Flaky)\]"


  centos:
    docker:
      - image: quay.io/snowdrop/centos-circleci:latest

    environment:
      ANSIBLE_BIN_DIR=/home/circleci/.local/bin

    steps:
      - checkout

      - run:
          name: Install k8s
          command: |
            PB_DIR=sandbox/k8s
            ansible-playbook $PB_DIR/main.yml -i $PB_DIR/circle_hosts \
                --limit circleci \
                -c local \
                --tags k8s_cluster \
                --become  \
                -e install_docker=false

  ubuntu:
    docker:
      - image: circleci/golang:latest

    environment:
      ANSIBLE_BIN_DIR=/home/circleci/.local/bin

    steps:
      - checkout

      - run:
          name: Install Ansible using pip3
          command: |
            sudo apt install -yqq python3-pip tree
            pip3 install ansible

      - run:
          name: Install k8s
          command: |
            PB_DIR=sandbox/k8s
            $ANSIBLE_BIN_DIR/ansible-playbook $PB_DIR/main.yml -i $PB_DIR/circle_hosts --limit circleci -c local --tags k8s_cluster --become

workflows:
  version: 2
  k8s-centos:
    jobs:
      - kind
      # - centos
      # k8s-ubuntu:
      #   jobs:
      #     - ubuntu

