version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:latest

    steps:
      - checkout

      - run:
          name: Install Ansible
          command: |
            apt -yqq install software-properties-common
            apt-add-repository ppa:ansible/ansible
            apt -yqq install ansible
