version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:latest

    steps:
      - checkout

      - run:
          name: Install Ansible using pip3
          command: |
            sudo apt install -yqq python3-pip tree
            pip3 install ansible -vv

      - run:
          name: Create Ansible Playbook
          command: |
            tree /usr/local/lib/python3.5/dist-packages
            tree  ~/.local/bin
            ansible-playbook sandbox/helloworld.yml

