version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:latest

    environment:
      ANSIBLE_BIN_DIR=/home/circleci/.local/bin

    steps:
      - checkout

      - run:
          name: Install Ansible using pip3
          command: |
            sudo apt install -yqq python3-pip tree
            pip3 install ansible

      - run:
          name: Install k8s
          command: |
            PB_DIR=sandbox/k8s
            $ANSIBLE_BIN_DIR/ansible-playbook $PB_DIR/main.yml -i $PB_DIR/circle_hosts --tags k8s_cluster

