version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:latest

    steps:
      - checkout

      - run:
          name: Install Ansible
          command: |
            sudo apt-get -yqq install software-properties-common
            sudo apt-add-repository -yqq ppa:ansible/ansible
            sudo apt-get -yqq install ansible
