version: 2.1

jobs:
  centos:
    docker:
      - image: quay.io/snowdrop/centos-circleci

    environment:
      ANSIBLE_BIN_DIR=/home/circleci/.local/bin

    steps:
      - checkout

      - run:
          name: Install k8s
          command: |
            PB_DIR=sandbox/k8s
            ansible-playbook $PB_DIR/main.yml -i $PB_DIR/circle_hosts \
                --limit circleci \
                -c local \
                --tags k8s_cluster \
                --become  \
                -e install_docker=false -vv

  ubuntu:
    docker:
      - image: circleci/golang:latest

    environment:
      ANSIBLE_BIN_DIR=/home/circleci/.local/bin

    steps:
      - checkout

      - run:
          name: Install Ansible using pip3
          command: |
            sudo apt install -yqq python3-pip tree
            pip3 install ansible

      - run:
          name: Install k8s
          command: |
            PB_DIR=sandbox/k8s
            $ANSIBLE_BIN_DIR/ansible-playbook $PB_DIR/main.yml -i $PB_DIR/circle_hosts --limit circleci -c local --tags k8s_cluster --become

workflows:
  version: 2
  k8s-centos:
    jobs:
      - centos
  # k8s-ubuntu:
  #   jobs:
  #     - ubuntu

