version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:latest

    steps:
      - checkout

      - run:
          name: Install Ansible
          command: |
            sudo apt-add-repository ppa:ansible/ansible
            sudo apt install ansible
