version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:latest

    steps:
      - checkout

      - run:
          name: Install Ansible using pip3
          command: |
            sudo apt install -yqq python3-pip
            pip3 install ansible

      - run:
          name: Create Ansible Playbook
          command: |
            ls -la /usr/local/lib/python3.5
            ansible-playbook sandbox/helloworld.yml

