- name: Check if kubectl exists
  stat:
    path: /usr/local/bin/kubectl
  register: result

- name: Install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubeclient_version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '755'
  when: result.stat.exists == false

- name: Create KubeDB namespace
  command: kubectl --kubeconfig=$HOME/.kube/config create namespace {{ kubedb_namespace }}
  ignore_errors: true

- name: Fetch KubeDB bash script
  get_url:
    url: https://raw.githubusercontent.com/kubedb/cli/{{ kubedb_version }}/hack/deploy/kubedb.sh
    dest: $HOME/kubedb.sh
    mode: '0755'

- name: Check if kubedb.sh exists
  stat:
    path: $HOME/kubedb.sh
  register: result

- name: Install KubeDB
  shell: |
    export KUBECONFIG=$HOME/.kube/config
    $HOME/kubedb.sh --namespace={{ kubedb_namespace }}
  when: result.stat.exists == true
