- name: Fetch KubeDB bash script
  get_url:
    url: https://raw.githubusercontent.com/kubedb/cli/{{ kubedb_version }}/hack/deploy/kubedb.sh
    dest: $HOME/kubedb.sh
    mode: '0755'

- name: Check if kubedb.sh exists
  stat:
    path: $HOME/kubedb.sh
  register: result

- name: Uninstall Kube DB and purge the CRDs
  shell: |
    export KUBECONFIG=$HOME/.kube/config
    $HOME/kubedb.sh --namespace={{ kubedb_namespace }} --uninstall --purge
  when: result.stat.exists == true

- name: Delete KubeDB namespace
  shell: |
    {{ client_tool }} --kubeconfig=$HOME/.kube/config delete ns {{ kubedb_namespace }}
