- name: "Generate inventory files on the controller"
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Test multi-line shell
      shell: |
        pwd
        cd /
        pwd
        cd {{ ansible_user_dir }}
        pwd
      register: shell_res
      tags: ['aaa','bbb']

    - name: Debug shell_res
      debug:
        msg:
          - "shell_res: {{ shell_res }}"
      tags: ['aaa','bbb']

    - name: Debug shell_res
      debug:
        msg:
          - "inventory_dir: {{ ansible_inventory_dir }}"
      tags: ['bbb']

...