- name: Generate PVC file
  template:
    src: pvc.yml.j2
    dest: /tmp/pvc.yml

- name: Generate Service file
  template:
    src: service.yml.j2
    dest: /tmp/service.yml

- name: Generate ReplicationController file
  template:
    src: replication-controller.yml.j2
    dest: /tmp/replication-controller.yml

- name: Install PVC
  shell: |
    kubectl apply -f /tmp/pvc.yml -n {{ docker_registry_namespace }}

- name: Install Replication Controller
  shell: |
    kubectl apply -f /tmp/replication-controller.yml -n {{ docker_registry_namespace }}

- name: Install Service
  shell: |
    kubectl apply -f /tmp/service.yml -n {{ docker_registry_namespace }}

- name: Get Service ClusterIP
  command: kubectl get service/kubernetes-dashboard -n kube-system -o jsonpath='{.spec.clusterIP}'
  register: clusterIPAddress

- name: Set fact
  set_fact:
    ip_cluster: clusterIPAddress.stdout

- name: Generate Server crt
  import_tasks: generate_server_crt.yml

