- set_fact:
    namespace: "{{ infra_project | default('infra') }}"

- name: Use Infra namespace/project
  command: oc {{ openshift_env.oc_admin_kubeconfig_arg }} new-project  {{ namespace }}
  ignore_errors: true

- name: Install Jaeger
  shell: |
    oc {{ openshift_env.oc_admin_kubeconfig_arg }} process -f https://raw.githubusercontent.com/jaegertracing/jaeger-openshift/master/all-in-one/jaeger-all-in-one-template.yml | oc {{ openshift_env.oc_admin_kubeconfig_arg }} -n {{ namespace }} create -f -
    oc {{ openshift_env.oc_admin_kubeconfig_arg }} expose service jaeger-collector --port=14268 -n {{ namespace }}
