- name: Create namespace if it doesn't exist
  command: "{{ client_tool }} {{ k8s_config }} create namespace {{ snowdrop_namespace }}"
  ignore_errors: true

- name: Deploy Snowdrop site application
  shell: |
    {{ client_tool }} {{ k8s_config }} -n {{ snowdrop_namespace }} apply -f https://raw.githubusercontent.com/snowdrop/snowdrop-site-angular/master/deploy/k8s/02_deployment.yml
    {{ client_tool }} {{ k8s_config }} -n {{ snowdrop_namespace }} apply -f https://raw.githubusercontent.com/snowdrop/snowdrop-site-angular/master/deploy/k8s/03_service.yml
    {{ client_tool }} {{ k8s_config }} -n {{ snowdrop_namespace }} apply -f https://raw.githubusercontent.com/snowdrop/snowdrop-site-angular/master/deploy/k8s/04_ingress.yml
