- name: Create namespace if it doesn't exist
  command: "{{ client_tool }} {{ k8s_config }} create namespace {{ snowdrop_namespace }}"
  ignore_errors: true

- name: Copy Deployment yml file to temp directory
  copy:
    src: "{{ role_path }}/files/deployment.yml"
    dest: /tmp/snowdrop.yml

# - name: Download the list of the resources to be deployedfor the site
#   get_url:
#     url: https://raw.githubusercontent.com/snowdrop/snowdrop-site-angular/master/openshift/snowdrop-site.yaml
#     dest: /tmp/snowdrop.yml

- name: Deploy Snowdrop site application
  command: "{{ client_tool }} {{ k8s_config }} apply -f /tmp/snowdrop.yml -n {{ snowdrop_namespace }}"
