- name: Remove SnowDrop web site k8s resources
  shell: |
    {{ client_tool }} {{ k8s_config }} -n {{ snowdrop_namespace }} delete -f https://raw.githubusercontent.com/snowdrop/snowdrop-site-angular/master/deploy/k8s/02_deployment.yml
    {{ client_tool }} {{ k8s_config }} -n {{ snowdrop_namespace }} delete -f https://raw.githubusercontent.com/snowdrop/snowdrop-site-angular/master/deploy/k8s/03_service.yml
    {{ client_tool }} {{ k8s_config }} -n {{ snowdrop_namespace }} delete -f https://raw.githubusercontent.com/snowdrop/snowdrop-site-angular/master/deploy/k8s/04_ingress.yml
    {{ client_tool }} {{ k8s_config }} -n {{ snowdrop_namespace }} delete -f https://raw.githubusercontent.com/snowdrop/snowdrop-site-angular/master/deploy/k8s/01_namespace.yml
