- name: Generate PVC file
  template:
    src: pvc.yml.j2
    dest: /tmp/pvc.yml

- name: Generate Service file
  template:
    src: service.yml.j2
    dest: /tmp/service.yml

- name: Install PVC
  shell: |
    {{ client_tool }} --kubeconfig={{ ansible_user_dir }}/.kube/config apply -f /tmp/pvc.yml -n {{ registry.namespace }}

- name: Install Service
  shell: |
    {{ client_tool }} --kubeconfig={{ ansible_user_dir }}/.kube/config apply -f /tmp/service.yml -n {{ registry.namespace }}

- name: Generate Server crt
  import_tasks: generate_server_crt.yml

- name: Generate ReplicationController file
  template:
    src: replication-controller.yml.j2
    dest: /tmp/replication-controller.yml

- name: Install Replication Controller
  shell: |
    {{ client_tool }} --kubeconfig={{ ansible_user_dir }}/.kube/config apply -f /tmp/replication-controller.yml -n {{ registry.namespace }}

