- name: Check if oc binary exists
  stat:
    path: "{{ openshift_client_dest }}/oc"
  register: oc_client

- name: Get the client assets
  include_tasks: get_client_assets.yml

- name: Install the oc binary client
  include_tasks: install_oc_client.yml
  when: not oc_client.stat.exists or openshift_force_client_install