- name: "Install misc kubernetes modules"
  hosts: "local"
  gather_facts: "{{ gathering_host_info | default('true') | bool == true }}"

  # Define default values for variables that are common between roles
  vars:
    client_tool: kubectl

  roles:
    - { role: 'kind',   tags: 'kind'}
