- name: Remove Component resources
  shell: |
    {{ client_tool }} delete sa {{ component_operator_name }} -n {{ component_operator_namespace }}
    {{ client_tool }} delete deployment {{ component_operator_name }} -n {{ component_operator_namespace }}
    {{ client_tool }} delete clusterrole {{ component_operator_name }}
    {{ client_tool }} delete clusterrolebinding {{ component_operator_name }}--role-binding
    {{ client_tool }} delete crd components.component.k8s.io
  ignore_errors: true
