- name: Create namespace if it doesn't exist
  command: "{{ client_tool }} {{ k8s_config }} create namespace {{ generator_namespace }}"
  ignore_errors: true

- name: Fetch Generator yml file using URL and version defined
  get_url:
    url: "https://raw.githubusercontent.com/snowdrop/generator/v{{ generator_version}}/conf/generator.yaml"
    dest: /tmp/generator.yaml

- name: Fetch the Deployment yml file using the URL and version defined
  get_url:
    url: "https://raw.githubusercontent.com/snowdrop/generator/v{{ generator_version}}/config/k8s/01_deployment.yml"
    force: yes
    dest: /tmp/deployment.yml

# - name: Cat application
#   command: cat /tmp/deployment.yml
#   register: application
#
# - name: Show Application file
#   debug: msg="Application file {{ application.stdout }}"

- name: Change the image version to use the one specified
  replace:
    path: "/tmp/deployment.yml"
    regexp: "latest"
    replace: "{{ generator_version }}"

# - name: Cat Application
#   command: cat /tmp/deployment.yml
#   register: application_modified
#
# - name: Show Application modified file
#   debug: msg="New Application file {{ application_modified.stdout }}"

- name: Create the Generator configmap using the downloaded file
  command: "{{ client_tool }} {{ k8s_config }} create configmap {{ generator_configmap_name }} --from-file /tmp/generator.yaml -n {{ generator_namespace }}"

- name: Deploy the Code Generator application
  shell: |
    {{ client_tool }} {{ k8s_config }} apply -f /tmp/deployment.yml -n {{ generator_namespace }}
    {{ client_tool }} {{ k8s_config }} apply -f https://raw.githubusercontent.com/snowdrop/generator/v{{ generator_version}}/config/k8s/02_service.yml -n {{ generator_namespace }}
    {{ client_tool }} {{ k8s_config }} apply -f https://raw.githubusercontent.com/snowdrop/generator/v{{ generator_version}}/config/k8s/03_ingress.yml -n {{ generator_namespace }}
