- name: Create namespace if it doesn't exist
  command: "{{ client_tool }} {{ k8s_config }} create namespace {{ generator.namespace }}"
  ignore_errors: true

- name: Fetch Generator yml file using URL and version defined
  get_url:
    url: "https://raw.githubusercontent.com/snowdrop/generator/v{{ generator.version}}/conf/generator.yaml"
    dest: /tmp/generator.yaml

- name: Fetch the Deployment yml file using the URL and version defined
  get_url:
    url: "https://raw.githubusercontent.com/snowdrop/generator/v{{ generator.version}}/config/k8s/generator-application.yml"
    dest: /tmp/application.yaml

- name: Change the image version to use the one specified
  replace:
    path: "/tmp/application.yaml"
    regexp: "latest"
    replace: "{{ generator.version }}"

# - name: Cat deployment
#   command: cat /tmp/application.yaml
#   register: temp_output

# - name: Show Deployment modified file
#   debug: msg="New deployment file {{ temp_output.stdout }}"

- name: Create the Generator configmap using the downloaded file
  command: "{{ client_tool }} {{ k8s_config }} create configmap {{ generator.configmap_name }} --from-file /tmp/generator.yaml -n {{ generator.namespace }}"

- name: Deploy the Code Generator application
  command: "{{ client_tool }} {{ k8s_config }} apply -f /tmp/application.yaml -n {{ generator.namespace }}"
