- name: Remove the configmap Generator
  command: "{{ client_tool }} {{ k8s_config }} delete configmap {{ generator_configmap_name }} -n {{ generator_namespace }}"

- name: Remove the Code Generator application
  shell: |
    {{ client_tool }} {{ k8s_config }} delete deployment/{{ generator_name }} -n {{ generator_namespace }}
    {{ client_tool }} {{ k8s_config }} delete service/{{ generator_name }} -n {{ generator_namespace }}
    {{ client_tool }} {{ k8s_config }} delete ingress/{{ generator_name }} -n {{ generator_namespace }}

- name: Delete the namespace
  command: "{{ client_tool }} {{ k8s_config }} delete ns {{ generator_namespace }}"


