- name: Remove the configmap Generator
  command: "{{ client_tool }} {{ k8s_config }} delete configmap {{ generator_configmap_name }} -n {{ generator_namespace }}"

- name: Remove the Code Generator application
  command: "{{ client_tool }} {{ k8s_config }} delete -f https://raw.githubusercontent.com/snowdrop/generator/v{{ generator_version }}/config/k8s/generator-application.yml -n {{ generator_namespace }}"

- name: Delete the namespace
  command: "{{ client_tool }} {{ k8s_config }} delete ns {{ generator_namespace }}"


