---
# tasks for hetzner/stop_server
- name: Start server
  command: "hcloud server poweron {{ vm_name }}"
  register: hetzner_server_poweron_res
  changed_when: "hetzner_server_poweron_res.rc == 0"
...