- name: Ensure no old docker version is installed
  yum:
    name: docker,docker-client,docker-client-latest,docker-common,docker-latest,docker-latest-logrotate,docker-logrotate,docker-engine
    state: absent
    # THIS OPTION OLY WORKS WITH ANSIBLE 2.8
    # lock_timeout: 1000

- name: Install dependencies needed by docker
  yum:
    name: yum-utils,device-mapper-persistent-data,lvm2
    state: present

- name: Add docker repository
  yum_repository:
    name: docker
    description: Docker
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: 1
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install docker
  yum:
    name: docker-ce-18.06.2.ce
    state: present

- name: Ensures /etc/docker dir exists
  file: path=/etc/docker state=directory

- name: Copy docker daemon.json file
  template:
    src: "daemon.json.j2"
    dest: /etc/docker/daemon.json

- name: Start docker
  systemd:
    state: restarted
    name: docker
    enabled: yes
