- name: Copy sa pv recycler controller file to master
  copy:
    src: "{{ role_path }}/files/sa-pv-recyler-controller.yml"
    dest: /tmp/sa-pv-recyler-controller.yml

- name: Define scc security for the pv-recycler-controller
  shell: |
    oc {{ openshift_env.oc_admin_kubeconfig_arg }} adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:openshift-infra:pv-recycler-controller
    oc {{ openshift_env.oc_admin_kubeconfig_arg }} create -f /tmp/sa-pv-recyler-controller.yml
  ignore_errors: true
