# To be included for every pv that is to be created:
# Expects the following vars to be defined:
#  volume_name, volume_storage, volume_reclaim_policy

- set_fact:
    pv_mount_directory: /tmp/{{ volume_name }}
    pv_definition_file: /tmp/{{ volume_name }}-def.yml

- name: Create internal mount directory
  shell: |
    mkdir -p {{ pv_mount_directory }}
    chmod -R 777 {{ pv_mount_directory }}
    chmod -R a+w {{ pv_mount_directory }}
    chcon -Rt svirt_sandbox_file_t {{ pv_mount_directory }}
  ignore_errors: true

- name: Delete pv {{ pv_name }}
  command: "oc {{ openshift_env.oc_admin_kubeconfig_arg }} delete pv/{{ volume_name }} --ignore-not-found=true"

- name: Copy pv file to master
  template:
    src: "{{ role_path }}/files/pv.yml.j2"
    dest: "{{ pv_definition_file }}"

- name: Create pv {{ pv_name }}
  command: "oc {{ openshift_env.oc_admin_kubeconfig_arg }} create -f {{ pv_definition_file }}"