- name: Setup security
  import_tasks: config_role_sa.yml

- name: Create persistence volume
  include_tasks: create_single_pv.yml
  vars:
    volume_name: "{{ volume_name_prefix }}{{ item }}"
  with_sequence: start={{ first_volume_offset }} count={{ number_of_volumes }} format=%03d