---
# tasks file for common
- name: firewalld - Manage masquerade
  firewalld:
    masquerade: "{{ firewalld_masquerade }}"
    zone: "{{ firewalld_zone }}"
    permanent: yes
    state: enabled
  become: yes
  notify: Restart firewalld
...
