---
# tasks file for common
- name: firewalld - Manage firewall sources
  firewalld:
    source: "{{ firewalld_source }}"
    zone: "{{ firewalld_zone }}"
    permanent: yes
    state: enabled
  become: yes
  notify: Restart firewalld
...
