apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: s2i-jdk8
spec:
  inputs:
    params:
      - name: BUILDER_IMAGE
        description: The location of the builder image.
        default: docker.io/kbaig/s2i
      - name: S2I_IMAGE
        description: The location of the s2i builder image.
        default: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
      - name: BUILDAH_IMAGE
        description: The location of the s2i builder image.
        default: quay.io/openshift-pipeline/buildah
      - name: TLSVERIFY
        description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
        default: "true"
    resources:
      - name: git-repo
        type: git
  outputs:
    resources:
      - name: image
        type: image
  steps:
    - name: s2ibuild
      image: ${inputs.params.BUILDER_IMAGE}
      command:
      - s2i
      # image: quay.io/chmouel/source-to-image:latest
      # command:
      # - /usr/local/bin/s2i
      args:
      - build
      - ${inputs.resources.git-repo.url}
      - ${inputs.params.S2I_IMAGE}
      - ${outputs.resources.image.url}
      volumeMounts:
      - name: docker-sock-volume
        mountPath: /var/run/docker.sock
      securityContext:
        privileged: true

    - name: docker-push
      image: gcr.io/cloud-builders/docker
      args:
      - push
      - ${outputs.resources.image.url}
      volumeMounts:
      - name: docker-sock-volume
        mountPath: /var/run/docker.sock

    # - name: buildah-push
    #   image: ${inputs.params.BUILDAH_IMAGE}
    #   command:
    #   - buildah
    #   args:
    #   - push
    #   - --tls-verify=${inputs.params.TLSVERIFY}
    #   - ${outputs.resources.image.url}
    #   - docker://${outputs.resources.image.url}
    #   volumeMounts:
    #   - name: docker-sock-volume
    #     mountPath: /var/run/docker.sock
    #   securityContext:
    #     privileged: true

  volumes:
    - name: docker-sock-volume
      hostPath:
        path: /var/run/docker.sock
