---
- name: "Define host variables 1/2"
  set_fact:
    model: "{{ type | default('simple') }}"
    host_name: "{{ vm_name | default(ip_address) }}"

- name: "Define host variables 2/2"
  set_fact:
    file_name: "{{ filename | default(model + '_hosts') }}"
    vm_vars: "{{ hostvars[host_name] }}"

- include_tasks: osev3.yml
  when: " type == 'cloud' "

- include_tasks: simple.yml
  when: " type == 'simple' "

- include_tasks: hetzner.yml
  when: " type == 'hetzner' "

- name: Refresh the inventory so the newly added host is available
  meta: refresh_inventory

...