---
- name: Define host type
  set_fact:
    model: "{{ type | default('simple') }}"
    file_name: "{{ model }}_host"
  when: filename == ""

- name: "Define host type [cloud, hetzner, simple, ["
  set_fact:
    model: "{{ type | default('simple') }}"
    file_name: "{{ filename }}"
  when: filename != ""

#- name: Create Ansible Host var file
#  template:
#    src: "{{ role_path }}/templates/{{ model }}.inventory.j2"
#    dest: "{{ inventory_relative_path }}/{{ file_name }}"

- include_tasks: osev3.yml
  when: " type == 'cloud' "

- include_tasks: simple.yml
  when: " type == 'simple' "

- include_tasks: hetzner.yml
  when: " type == 'hetzner' "

- name: Refresh the inventory so the newly added host is available
  meta: refresh_inventory

...