apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: s2i-buildah-springboot
spec:
  serviceAccount: build-bot
  taskRef:
    name: s2i-buildah
  inputs:
    params:
    - name: baseImage
      value: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
    - name: verifyTLS
      value: "false"
    - name: contextFolder
      value: /workspace/
    resources:
    - name: workspace-git
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/snowdrop/rest-http-example
  outputs:
    resources:
    - name: image
      resourceSpec:
        type: image
        params:
        - name: url
          value: quay.io/snowdrop/spring-boot-example

