apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: s2i-springboot
spec:
  serviceAccount: build-bot
  taskRef:
    name: s2i-buildah
  inputs:
    resources:
    - name: git-repo
      resourceSpec:
        type: git
        params:
          - name: url
            value: https://github.com/snowdrop/rest-http-example
  outputs:
    resources:
    - name: image
      resourceSpec:
        type: image
        params:
          - name: url
            value: quay.io/snowdrop/spring-boot-example

